[package]
name = "GeneticMicroservice"
version = "0.1.0"
authors = ["sremedios <sam.remedios@gmail.com>"]

[dependencies]
serde = "1"
serde_json = "1"
serde_derive = "1"
rand = "0.3"
rsgenetic = "1.7.14"
base64 = "0.9"
byteorder = "1"
